// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epegfjbxazwbgblfbkpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwZWdmamJ4YXp3YmdibGZia3BqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NjI0MTQsImV4cCI6MjA1OTIzODQxNH0.YBg8FAp-bV64OgUSmAQfOCKIJxIss2rtkPeLVoqSVrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);